version: "3.5"
services:
  influxdb:
    image: influxdb:1.8-alpine
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    volumes:
      - influxdb:/var/lib/influxdb
    networks: [org]

  loki:
    image: grafana/loki:2.8.8
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki:/loki
    networks: [org]

  telegraf:
    image: telegraf:1.32.0-alpine
    restart: no
    depends_on: [influxdb, loki]
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks: [org]
    environment:
      - TOKEN=${TOKEN}
      - SPONSORID=${SPONSORID}
      - SFHID=${SFHID}
      - PROVIDERID=${PROVIDERID}
      - APPID=${APPID}
      - NATS=${NATS}

  grafana:
    image: grafana/grafana:10.2.4
    depends_on: [influxdb, loki]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=
    ports:
      - "33000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning/
    networks: [org]

volumes:
  influxdb: {}
  grafana: {}
  loki: {}

networks:
  org:
    name: org
